language: python

matrix:
  include:
    - name: "Python 3.7 on Linux Ubuntu Xenial"
      python: 3.7
      dist: xenial
    - name: "Python 3.6 on Linux"
      python: 3.6
    - name: "Python 3.5 on Linux"
      python: 3.5
    - name: "Python 3.4 on Linux"
      python: 3.4

addons:
  apt:
    packages:
      - python-docutils

sudo: true
cache: pip

install:
  - pip install .
  - pip install -r requirements.txt

before_script:
  - cp -v .travis/backupctl.ini backupctl.ini

script:
  - make test
  - make man

# vim: set ts=2 sw=2 :
