language: python

python:
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install .
  - pip install -r requirements.txt

script:
  - py.test --cov=bkpmgmt bkpmgmt
  - isort -df -vb -ns "__init__.py" -sg "" -s "" -rc -c -p bkpmgmt bkpmgmt
  - make man

# vim: set ts=2 sw=2 :
