language: python

python:
  - 3.4
  - 3.5
  - 3.6

addons:
  apt:
    packages:
      - python-docutils

sudo: true
cache: pip

install:
  - pip install .
  - pip install -r requirements.txt

before_script:
  - cp -v .travis/backupctl.ini backupctl.ini

script:
  - make test
  - make man

# vim: set ts=2 sw=2 :
